#!/bin/bash
set -o xtrace

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
for dotfile in $(ls -A $SCRIPT_DIR | grep \\. | grep -v git) ; do
  ln "$SCRIPT_DIR/$dotfile" ~/"$dotfile"
done

